[package]
name = "Reliure"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
chrono = "0.4.39"
derive-new = "0.7.0"
rusqlite = {version = "0.32.1", features = ["bundled"]}
serde = "1.0.216"
tokio = {version = "1.42.0", features = ["full"]}
